import Head from "next/head"
import { useState } from "react"
import Image from "next/image"
import Navigation from "../components/navigation"
import { motion } from "framer-motion"
import ReactPageScroller from "react-page-scroller"
import { useNavContext } from "../context/navigation"

export default function Home({}) {
   const [menuOpen, setMenuOpen, modalOpen, setModalOpen] = useNavContext()

   const variants = {
      open: {
         opacity: 1,
         x: -1000,
         transition: { duration: 1.5, ease: [0.43, 0.13, 0.23, 0.96] },
      },
      closed: {
         opacity: 1,
         x: 0,
         transition: { duration: 1.5, ease: [0.43, 0.13, 0.23, 0.96] },
      },
   }

   const variants2 = {
      open: {
         opacity: 1,
         x: 1000,
         transition: { duration: 1.3, ease: [0.43, 0.13, 0.23, 0.96] },
      },
      closed: {
         opacity: 1,
         x: 0,
         transition: { duration: 1.3, ease: [0.43, 0.13, 0.23, 0.96] },
      },
   }

   const transition = { duration: 1.3, ease: [0.43, 0.13, 0.23, 0.96] }
   return (
      <>
         <Head>
            <title>About Me | Portfolio - Sven Rehm</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <motion.div className="flex justify-between h-screen overflow-hidden">
            <motion.div
               className="w-[40%] mt-[250px] pl-[70px]"
               initial={{ opacity: 0, x: -1000 }}
               exit={{ opacity: 0, x: -1000 }}
               transition={transition}
               animate={menuOpen ? "open" : "closed"}
               variants={variants}
            >
               <h1 className="text-6xl mb-[70px]">
                  Web Design That Works for You:
                  <br></br>Sven&apos;s Philosophy
               </h1>

               <p className="text-2xl leading-normal mb-[70px]">
                  Hello, my name is [Your Name] and I am a web designer. I have
                  a passion for creating visually appealing and user-friendly
                  websites that drive results. With a focus on responsive design
                  and SEO best practices, I am eager to help businesses of all
                  sizes establish a strong online presence and reach their
                  target audiences. Let&apos;s work together to create a website
                  that truly stands out from the competition.
               </p>
            </motion.div>
            <motion.div
               className="w-[50%] h-full"
               initial={{ opacity: 0, x: 1000 }}
               exit={{ opacity: 0, x: 1000 }}
               transition={transition}
               animate={menuOpen ? "open" : "closed"}
               variants={variants2}
            >
               <img
                  className="object-cover w-full h-full"
                  src="/hero.jpg"
                  alt="image"
               />
            </motion.div>
         </motion.div>
      </>
   )
}

export async function getStaticProps() {
   return {
      props: {},
   }
}
