import Head from "next/head"
import { useState } from "react"
import Image from "next/image"
import Navigation from "../components/navigation"
import ReactPageScroller from "react-page-scroller"
export default function Home({}) {
   const [menuOpen, setMenuOpen] = useState(false)
   const [selectedTable, setSelectedTable] = useState()

   //click
   function clicky() {}
   let options = {
      animationTimer: 850,
      animationTimerBuffer: 0,
      renderAllPagesOnFirstRender: true,
   }

   return (
      <>
         <Head>
            <title>About Me | Portfolio - Sven Rehm</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <div className="flex justify-between h-screen ">
            <div className="w-[40%] mt-[250px] pl-[70px]">
               <h1 className="text-6xl mb-[70px]">
                  Web Design That Works for You:
                  <br></br>Sven&apos;s Philosophy
               </h1>

               <p className="text-2xl leading-normal mb-[70px]">
                  Hello, my name is [Your Name] and I am a web designer. I have
                  a passion for creating visually appealing and user-friendly
                  websites that drive results. With a focus on responsive design
                  and SEO best practices, I am eager to help businesses of all
                  sizes establish a strong online presence and reach their
                  target audiences. Let&apos;s work together to create a website
                  that truly stands out from the competition.
               </p>
            </div>
            <div className="w-[50%] h-full">
               <img
                  className="object-cover w-full h-full"
                  src="/hero.jpg"
                  alt="image"
               />
            </div>
         </div>
      </>
   )
}

export async function getStaticProps() {
   return {
      props: {},
   }
}
