import Head from "next/head"
import { useState } from "react"
import Image from "next/image"
import Link from "next/link"
import ReactPageScroller from "react-page-scroller"
import { motion } from "framer-motion"
import { AnimatePresence } from "framer-motion"
import { useNavContext } from "../context/navigation"

const transition = { duration: 0.6, ease: [0.43, 0.13, 0.23, 0.96] }

const variants = {
   open: {
      opacity: 0,
      y: -500,
      transition: { duration: 2, ease: [0.43, 0.13, 0.23, 0.96] },
   },
   closed: {
      opacity: 1,
      y: 0,
      transition: { duration: 1.5, ease: [0.43, 0.13, 0.23, 0.96] },
   },
}

const variants2 = {
   open: {
      opacity: 0,
      top: "-50%",
      transition: { duration: 1, ease: [0.43, 0.13, 0.23, 0.96] },
   },
   closed: {
      opacity: 1,
      top: "50%",
      transition: { delay: 1, duration: 1, ease: [0.43, 0.13, 0.23, 0.96] },
   },
}

export default function Home({}) {
   const [selectedTable, setSelectedTable] = useState()
   const [menuOpen, setMenuOpen] = useNavContext()

   //click
   function clicky() {}

   let options = {
      animationTimer: 850,
      animationTimerBuffer: 0,
      renderAllPagesOnFirstRender: true,
   }

   return (
      <>
         <Head>
            <title>HomePage portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <ReactPageScroller
            {...options}
            ref={(c) => (this.reactPageScroller = c)}
         >
            <motion.div className="flex items-center justify-center h-[100vh] px-[70px] ">
               <div className="overflow-hidden">
                  <div className="w-1/2 ">
                     <div className="overflow-hidden">
                        <motion.h1
                           animate={menuOpen ? "open" : "closed"}
                           variants={variants}
                           className="text-6xl"
                        >
                           Hello my name is
                        </motion.h1>
                     </div>
                     <div className="overflow-hidden">
                        <motion.h1
                           animate={menuOpen ? "open" : "closed"}
                           variants={variants}
                           className="mb-10 text-6xl font-semibold"
                        >
                           Sven Rehm
                        </motion.h1>
                     </div>
                     <div className="overflow-hidden">
                        <motion.h3
                           animate={menuOpen ? "open" : "closed"}
                           variants={variants}
                           className="w-2/3 text-2xl"
                        >
                           Ich bin ein Frontend-Webentwickler mit einer
                           Leidenschaft für die Erstellung von sauberen und
                           benutzerfreundlichen Webseiten.
                        </motion.h3>
                     </div>
                  </div>
               </div>
               <div className="w-1/2">
                  {/* <Image
                     alt="me"
                     src="/img1.jpg"
                     width={200}
                     height={200}
                  ></Image> */}
               </div>
            </motion.div>

            <section className="h-[100vh] section">
               <div className="hiddenbyme">
                  <motion.div
                     animate={menuOpen ? "open" : "closed"}
                     variants={variants2}
                     className="overflow-hidden width-[1100px]    height-[450px]
                     top-1/2
                     left-1/2
                     transform -translate-x-1/2 -translate-y-1/2
                     relative
                     reflection"
                  >
                     <motion.h1
                        exit={{ opacity: 0 }}
                        transition={transition}
                        className="absolute z-50 text-5xl text-white transform -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2"
                     >
                        Portfolio
                     </motion.h1>
                     <Link href="/project" scroll={false}>
                        <motion.img
                           whileHover={{ scale: 1.1 }}
                           transition={transition}
                           src="/image.png"
                           alt="bla"
                        />
                     </Link>
                  </motion.div>
               </div>
            </section>
            <section className="h-[100vh] section">
               <div className="hiddenbyme">
                  <motion.div
                     animate={menuOpen ? "open" : "closed"}
                     variants={variants2}
                     className="overflow-hidden width-[1100px] height-[450px]
         
                     top-1/2
                     left-1/2
                     transform -translate-x-1/2 -translate-y-1/2
                     relative
                     "
                  >
                     <Link href="/project2" scroll={false}>
                        <motion.img
                           whileHover={{ scale: 1.1 }}
                           transition={transition}
                           src="/image4.png"
                           alt="bla"
                        />
                     </Link>
                  </motion.div>
               </div>
            </section>
            <section className="h-[100vh] section">
               <div className="hiddenbyme">
                  <motion.div
                     animate={menuOpen ? "open" : "closed"}
                     variants={variants2}
                     className="overflow-hidden width-[1100px] height-[450px]
         
                     top-1/2
                     left-1/2
                     transform -translate-x-1/2 -translate-y-1/2
                     relative
                     "
                  >
                     <Link href="/project3" scroll={false}>
                        <motion.img
                           whileHover={{ scale: 1.1 }}
                           transition={transition}
                           src="/image2.png"
                           alt="bla"
                        />
                     </Link>
                  </motion.div>
               </div>
            </section>
         </ReactPageScroller>
      </>
   )
}

export async function getStaticProps() {
   return {
      props: {},
   }
}
