import Head from "next/head"
import { useState, useEffect } from "react"
//TODO
import Image from "next/image"
import Link from "next/link"
import ReactPageScroller from "react-page-scroller"
import { motion } from "framer-motion"

import { useNavContext } from "../context/navigation"
import { useInView } from "framer-motion"

const transition = { duration: 0.6, ease: [0.43, 0.13, 0.23, 0.96] }

const variants = {
   open: {
      opacity: 0,
      y: -500,
      transition: { duration: 2, ease: [0.43, 0.13, 0.23, 0.96] },
   },
   closed: {
      opacity: 1,
      y: 0,
      transition: { duration: 1.5, ease: [0.43, 0.13, 0.23, 0.96] },
   },
}

const variants2 = {
   open: {
      opacity: 0,
      top: "-50%",
      transition: { duration: 1, ease: [0.43, 0.13, 0.23, 0.96] },
   },
   closed: {
      opacity: 1,
      top: "50%",
      transition: { delay: 1, duration: 1, ease: [0.43, 0.13, 0.23, 0.96] },
   },
}

export default function Home({}) {
   const [selectedTable, setSelectedTable] = useState()
   const [menuOpen, setMenuOpen] = useNavContext()

   useEffect(() => {
      console.log("Element is in view: ")
   }, [])

   let options = {
      animationTimer: 850,
      animationTimerBuffer: 0,
      renderAllPagesOnFirstRender: true,
      onBeforePageScroll: () => {
         //TODO
         console.log("before scroll add state to component with animation")
      },
   }

   return (
      <>
         <Head>
            <title>HomePage portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <ReactPageScroller
            {...options}
            ref={(c) => (this.reactPageScroller = c)}
         >
            <motion.div className="flex items-center justify-center   h-[100vh] px-[70px] ">
               <div className="w-1/2 ">
                  <div className="overflow-hidden">
                     <motion.h1
                        animate={menuOpen ? "open" : "closed"}
                        variants={variants}
                        className="font-bold text-7xl"
                     >
                        HALLO,
                        <span className="mb-10 text-6xl font-normal">
                           {" "}
                           mein name ist
                        </span>
                     </motion.h1>
                     <h1 className="mb-10 text-[90px] font-bold">SVEN REHM</h1>
                  </div>
                  <div className="mb-10 overflow-hidden">
                     <motion.h3
                        animate={menuOpen ? "open" : "closed"}
                        variants={variants}
                        className="text-3xl leading-normal font-opensans"
                     >
                        Ich bin ein{" "}
                        <span className="font-bold">
                           Webdesigner/Entwickler
                        </span>
                        <br></br>
                        mit einer passion für die erschaffung von
                        atemberaubenden Webseiten.
                     </motion.h3>
                  </div>

                  <Link href="/portfolio" className="relative text-3xl meins">
                     Portfolio
                  </Link>
                  <Link
                     href="/portfolio"
                     className="relative ml-10 text-3xl meins"
                  >
                     Portfolio
                  </Link>
               </div>

               <div className="flex items-center justify-end w-1/2 ">
                  <Image
                     alt="me"
                     src="/img1.jpg"
                     width={600}
                     height={600}
                  ></Image>
               </div>
            </motion.div>

            <section className="h-[100vh] section relative">
               <div
                  className="relative overflow-hidden hiddenbyme top-1/2 left-1/2 
                  w-[1100px]
                  h-[450px] transform -translate-x-1/2 -translate-y-1/2 "
                  // className="width-[1100px] heigth-[450px] top-1/2 left-1/2 relative transform -translate-x-1/2 -translate-y-1/2 overflow-hidden "
               >
                  <motion.div
                     animate={menuOpen ? "open" : "closed"}
                     variants={variants2}
                     //need w and h
                     className="w-[1100px] h-[450px] relative transform -translate-x-1/2 -translate-y-1/2 left-1/2  overflow-hidden"
                  >
                     <Link href="/project" scroll={false}>
                        <motion.h1
                           exit={{ opacity: 0 }}
                           transition={transition}
                           className="absolute z-50 text-5xl text-white transform -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2"
                        >
                           Portfolio
                        </motion.h1>

                        <motion.img
                           whileHover={{ scale: 1.1 }}
                           transition={transition}
                           src="/image.png"
                           alt="bla"
                        />
                     </Link>
                  </motion.div>
               </div>
            </section>
            {/* <section className="h-[100vh] section">
               <div className="hiddenbyme">
                  <motion.div
                     animate={menuOpen ? "open" : "closed"}
                     variants={variants2}
                     className="overflow-hidden width-[1100px] height-[450px]
         
                     top-1/2
                     left-1/2
                     transform -translate-x-1/2 -translate-y-1/2
                     relative
                     "
                  >
                     <Link href="/project2" scroll={false}>
                        <motion.img
                           whileHover={{ scale: 1.1 }}
                           transition={transition}
                           src="/image4.png"
                           alt="bla"
                        />
                     </Link>
                  </motion.div>
               </div>
            </section>
            <section className="h-[100vh] section">
               <div className="hiddenbyme">
                  <motion.div
                     animate={menuOpen ? "open" : "closed"}
                     variants={variants2}
                     className="overflow-hidden width-[1100px] height-[450px]
         
                     top-1/2
                     left-1/2
                     transform -translate-x-1/2 -translate-y-1/2
                     relative
                     "
                  >
                     <Link href="/project3" scroll={false}>
                        <motion.img
                           whileHover={{ scale: 1.1 }}
                           transition={transition}
                           src="/image2.png"
                           alt="bla"
                        />
                     </Link>
                  </motion.div>
               </div>
            </section> */}
         </ReactPageScroller>
      </>
   )
}

export async function getStaticProps() {
   return {
      props: {},
   }
}
