import Head from "next/head"
import { useState } from "react"
import Image from "next/image"
import { motion } from "framer-motion"
import useWindowDimensions from "../helper/window"

const transition = { duration: 1.4, ease: [0.6, 0.1, -0.05, 0.9] }
export default function Project({}) {
   const { height, width } = useWindowDimensions()

   return (
      <>
         <Head>
            <title>HomePage portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <div className="relative w-full h-[100vh]">
            <motion.div
               initial={{
                  width: 1100,
                  height: 450,
                  top: "50%",
                  left: "50%",
               }}
               animate={{
                  height: 450,
                  width: "100%",
                  top: 300,
                  left: "50%",
                  transition: { delay: 0.3, ...transition },
               }}
               className="w-[1100px] h-[450px]  relative transform -translate-x-1/2 -translate-y-1/2 left-1/2 overflow-hidden"
            >
               <motion.h1
                  initial={{
                     opacity: 0,
                  }}
                  animate={{
                     opacity: 1,
                     transition: { delay: 1.5, ...transition },
                  }}
                  exit={{ opacity: 0 }}
                  transition={transition}
                  className=" absolute z-50 text-5xl tracking-[40px] text-white transform -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2 font-[100] font-roboto"
               >
                  ANIMELIST
               </motion.h1>
               <motion.img
                  initial={{ scale: 1.1 }}
                  animate={{
                     y: -80,
                     transition: { delay: 0.2, ...transition },
                  }}
                  exit={{
                     opacity: 0,
                     transition: { ...transition },
                  }}
                  // src="/image.png"

                  src="/jepanime1.png"
                  alt="image"
                  className="w-full"
               />
               {/* <Image alt="me" src="/img1.jpg" width={"100%"} height={500}></Image> */}
            </motion.div>
            <div className="container m-auto">
               <div className="overflow-hidden">
                  <motion.h4
                     initial={{ y: 80 }}
                     animate={{
                        y: 0,
                        transition: { delay: 1.6, ...transition },
                     }}
                     className="text-xl font-roboto text-[#808080] mt-[200px]"
                  >
                     Project
                  </motion.h4>
                  <h1 className="font-bold text-black text-7xl font-playfair ">
                     Animelist
                  </h1>
                  <h3 className="text-6xl text-black font-playfair "></h3>
                  <motion.h4
                     initial={{ y: 80 }}
                     animate={{
                        y: 0,
                        transition: { delay: 1.6, ...transition },
                     }}
                     className="text-xl font-roboto text-[#808080] mt-[100px]"
                  >
                     Overview
                  </motion.h4>
                  <p className="text-2xl font-roboto text-black mt-[30px] w-1/2">
                     NS International is a large railway company based in The
                     Netherlands, with more than 3,300 European destinations.
                     They were looking for a way to increase their customer
                     satisfaction and online
                  </p>

                  <div className="flex">
                     <div className="w-1/2">
                        <motion.h4
                           initial={{ y: 80 }}
                           animate={{
                              y: 0,
                              transition: { delay: 1.6, ...transition },
                           }}
                           className="text-xl font-roboto text-[#808080] mt-[50px]"
                        >
                           Website
                        </motion.h4>
                        <a
                           href="https://deskanrhtc.net/"
                           target="_blank"
                           className="text-2xl font-roboto text-black mt-[30px]"
                           rel="noreferrer"
                        >
                           https://deskanrhtc.net/
                        </a>
                     </div>

                     <div className="w-1/2">
                        <motion.h4
                           initial={{ y: 80 }}
                           animate={{
                              y: 0,
                              transition: { delay: 1.6, ...transition },
                           }}
                           className="text-xl font-roboto text-[#808080] mt-[50px]"
                        >
                           Role
                        </motion.h4>
                        <h3 className="text-2xl font-roboto text-black mt-[30px]">
                           Frontend Developer, Web Designer
                        </h3>

                        <motion.h4
                           initial={{ y: 80 }}
                           animate={{
                              y: 0,
                              transition: { delay: 1.6, ...transition },
                           }}
                           className="text-xl font-roboto text-[#808080] mt-[50px]"
                        >
                           Technologies used
                        </motion.h4>
                        <h3 className="text-2xl font-roboto text-black mt-[30px]">
                           Html, Css, JS, React, AdobeXD
                        </h3>

                        <motion.h4
                           initial={{ y: 80 }}
                           animate={{
                              y: 0,
                              transition: { delay: 1.6, ...transition },
                           }}
                           className="text-xl font-roboto text-[#808080] mt-[50px]"
                        >
                           Year
                        </motion.h4>
                        <h3 className="text-2xl font-roboto text-black mt-[30px]">
                           2022
                        </h3>
                     </div>
                  </div>
               </div>
            </div>
            {/* grid */}
            <section class="text-gray-600 body-font">
               <div class=" py-24 mx-auto flex flex-wrap">
                  <div class="flex flex-wrap">
                     <div class="flex flex-wrap w-2/3">
                        <div class="w-full h-full mr-1 border border-[#EBEBEB]">
                           <img
                              alt="gallery"
                              class="w-full h-full object-cover object-left-bottom block"
                              src="/projectimages/hairflair/hairflair1.png"
                           />
                        </div>
                     </div>
                     <div class="flex flex-wrap w-1/3 ">
                        <div class="w-full mb-1 border border-[#EBEBEB] h-2/3 ">
                           <img
                              alt="gallery"
                              class="w-full h-full object-cover object-center block"
                              src="/image3.png"
                           />
                        </div>
                        <div class="w-full h-1/3 overflow-hidden border border-[#EBEBEB]">
                           <img
                              alt="gallery"
                              class="w-full object-cover object-center block"
                              src="/image2.png"
                           />
                        </div>
                     </div>
                  </div>
               </div>
            </section>
         </div>
      </>
   )
}

export async function getStaticProps() {
   return {
      props: {},
   }
}
