import Head from "next/head"
import { useState } from "react"
import Image from "next/image"
import { motion } from "framer-motion"
import useWindowDimensions from "../helper/window"

const transition = { duration: 1.4, ease: [0.6, 0.1, -0.05, 0.9] }
export default function Project({}) {
   const { height, width } = useWindowDimensions()

   return (
      <>
         <Head>
            <title>HomePage portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <div className="relative h-[100vh] w-full">
            <motion.div
               initial={{
                  width: 1100,
                  height: 450,
                  top: "50%",
                  left: "50%",
               }}
               animate={{
                  height: 350,
                  width: width,
                  top: 250,
                  left: "50%",
                  transition: { delay: 0.3, ...transition },
               }}
               className="w-[1100px] h-[450px]  relative transform -translate-x-1/2 -translate-y-1/2 left-1/2 overflow-hidden"
            >
               <motion.img
                  initial={{ scale: 1.1 }}
                  animate={{
                     y: -80,
                     transition: { delay: 0.2, ...transition },
                  }}
                  exit={{
                     opacity: 0,
                     transition: { ...transition },
                  }}
                  // src="/image.png"

                  src="/fate.jpeg"
                  alt="image"
                  className="w-full "
               />
               {/* <Image alt="me" src="/img1.jpg" width={"100%"} height={500}></Image> */}
            </motion.div>

            {/* <div class="overflow-hidden">
               <motion.h1
                  initial={{ y: 80 }}
                  animate={{
                     y: 0,
                     transition: { delay: 1.6, ...transition },
                  }}
                  className="font-bold text-7xl mt-[200px]"
               >
                  Hello
               </motion.h1>
            </div> */}
         </div>
      </>
   )
}

export async function getStaticProps() {
   return {
      props: {},
   }
}
